services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Symfony\Component\Serializer\Normalizer\CustomNormalizer: ~

    SymfonyOrchestra\ViewBundle\:
        resource: '../../*'
        exclude: '../../{Exception,View,PropertyAccessor}'