name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP 8.5
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          tools: composer:v2
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: |
            vendor
            ~/.composer/cache/files
          key: ${{ runner.os }}-php-8.4-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-8.4-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run test suite
        run: composer run-script test

      - name: Run PHPStan
        run: composer run-script analyse

      - name: Run PHP-CS-Fixer
        run: composer run-script cs-check
